### ISSUE TITLE
Typo in kiss.cow comment

### ISSUE THREAD

**Issue by GreenBeard** [cowsay-org/cowsay#17]
https://github.com/cowsay-org/cowsay/blob/cb41f5a94471911fe8c0760e0a530bb63a84a87a/share/cows/kiss.cow#L2

I believe that this is meant to say "embrace"

**Comment by apjanke** [comment]
Thank you! Fixed in https://github.com/cowsay-org/cowsay/commit/3bcb8ae79c139f2aaa216fb9fc225422f931e85e.
