### ISSUE TITLE
cowsay -r: "Cannot load cow from /usr/share/cowsay/cows/TextBalloon.pm: .pm format cows are not implemented yet. Sorry."

### ISSUE THREAD

**Issue by ndim** [cowsay-org/cowsay#22]
When running `cowsay -r`, occasionally cowsay fails with a message like

```
$ date | cowsay -r
cowsay: Cannot load cow from /usr/share/cowsay/cows/Frogs.pm: .pm format cows are not implemented yet. Sorry.
$ date | cowsay -r
cowsay: Cannot load cow from /usr/share/cowsay/cows/TextBalloon.pm: .pm format cows are not implemented yet. Sorry.
$ date | cowsay -r
cowsay: Cannot load cow from /usr/share/cowsay/cows/DragonAndCow.pm: .pm format cows are not implemented yet. Sorry.
$ _
```

I would expect `cowsay -r` to choose a random cow from all the available cows which actually work, and then use that. 

Quick command to reproduce: `while date | cowsay -r; do :; done`

A look into `/usr/share/cowsay/cows/` shows 7 `*.pm` files, one `mech-and-cow` file without a file extension, and a few dozen `*.cow` files.

Manually choosing a certain cow does not make the `*.pm` cows work either. The `mech-and-cow` (without file extension) cow does not work either, but triggers a different error:

```
$ date | cowsay -f MechAndCow.pm
cowsay: Cannot load cow from /usr/share/cowsay/cows/MechAndCow.pm: .pm format cows are not implemented yet. Sorry.
$ date | cowsay -f mech-and-cow
Backticks found where operator expected at /usr/share/cowsay/cows/mech-and-cow line 10, near "^__^                             /   /'|  `"
	(Missing semicolon on previous line?)
Backslash found where operator expected at /usr/share/cowsay/cows/mech-and-cow line 11, near ")\"
	(Missing operator before \?)
Backticks found where operator expected at /usr/share/cowsay/cows/mech-and-cow line 12, at end of line
	(Missing semicolon on previous line?)
cowsay: Error reading cow definition from /usr/share/cowsay/cows/mech-and-cow: Can't find string terminator "`" anywhere before EOF at /usr/share/cowsay/cows/mech-and-cow line 12, <STDIN> line 1.

$ _
```

And for completeness' sake:

```
$ cowsay --version
/usr/bin/cowsay version 3.7.0 calling Getopt::Std::getopts (version 1.13),
running under Perl version 5.34.1.
$ _
```

**Comment by apjanke** [comment]
> I would expect cowsay -r to choose a random cow from all the available cows which actually work, and then use that.

Your expectation is correct. The random-cow-selection code should be fixed to do this.

**Comment by ndim** [comment]
> > I would expect cowsay -r to choose a random cow from all the available cows which actually work, and then use that.
> 
> Your expectation is correct. The random-cow-selection code should be fixed to do this.

If all cow files worked, the selection code could remain unchanged. :-)

AFAICT, that would mean implementing support for the `*.pm` type and either converting the non-working `mech-and-cow` to the `*.cow` format or removing `mech-and-cow` in favour of the existing `MechAndCow.pm`.

I have not examined the differences between `.cow` and `.pm`, so I do not know what one offers over the other, and whether `.pm` is a legacy format or the future.

**Comment by apjanke** [comment]
I believe .pm is the future, and it allows you to build cows more dynamically, for whatever reason you might want to do that. But AFAICT, it never got implemented in the first place, and would take a bit of work, and I'm kinda busy. So that's why we don't have .pm support here yet.

Given that, I think the right move here is to exclude .pm cows from the random selection.

Unless *you'd* like to submit a PR with .pm cow support. ;)

**Comment by ndim** [comment]
> I believe the .pm cow format is the future (but as an optional alternative; the original .cow format will not go away and most people will still want to use it instead), and it allows you to build cows more dynamically, for whatever reason you might want to do that. But AFAICT, it never got implemented in the first place, and would take a bit of work, and I'm kinda busy. So that's why we don't have .pm support here yet.
> 
> Given that, I think the right move here is to exclude .pm cows from the random selection.

And remove the broken non-extension `mech-and-cow` file as well.

> Unless *you'd* like to submit a PR with .pm cow support. ;)

Hmm... Maybe. I have not done Perl in 20 to 25 years, and I have never written anything of consequence in Perl like a script longer than a few hundred lines, much less an API to last.

I could give it a try and re-learn some Perl. Do not hold your breath for that, though. This is not mission critical after all. Also, do not expect very good Perl API design or very good Perl code.

On the other hand, keeping old and more or less non-essential but still interesting software maintained at least to the point of keeping it running on contemporary systems is just my thing.

Lets see. A categorical maybe.

**Comment by apjanke** [comment]
> And remove the broken non-extension mech-and-cow file as well.

D'oh! Yeah, that too.

> Hmm... Maybe. ... I could give it a try and re-learn some Perl.

I was 100% joking here. I would not recommend this as a project if you have anything else interesting to do. :)

**Comment by ndim** [comment]
https://github.com/cowsay-org/cowsay/pull/26 will fix this.

**Comment by apjanke** [comment]
That #26 Makefile fix took care of this. And then I went further in https://github.com/cowsay-org/cowsay/issues/54 and moved the .pm stuff from the installation entirely. The .pm cows are no longer in the in-repo cows dir, and the cowfile-detection logic no longer recognizes .pm files as cows, so extraneous user-installed .pm cows won't get picked up either.

Closing as Fixed. Should go out in 3.8.3.
