### ISSUE TITLE
What is the point of the README (and INSTALL) file when there is README.md?

### ISSUE THREAD

**Issue by ndim** [cowsay-org/cowsay#29]
What is the point of the [`README`](https://github.com/cowsay-org/cowsay/blob/master/README) (and [`INSTALL`](https://github.com/cowsay-org/cowsay/blob/master/INSTALL)) file when there is [`README.md`](https://github.com/cowsay-org/cowsay/blob/master/README.md) which already contains all the information from [`README`](https://github.com/cowsay-org/cowsay/blob/master/README) and [`INSTALL`](https://github.com/cowsay-org/cowsay/blob/master/INSTALL)?

**Comment by apjanke** [comment]
Friendliness to Linux greybeards and old tools (programmatic tools; that's not an insult) that like plain text and will only look for a plain `README` first. :) The `README` is basically just a human-readable redirect to `README.md`.

**Comment by ndim** [comment]
README.md is markdown is human readable.
