### ISSUE TITLE
Plans for new release?

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [cowsay-org/cowsay#41]
As I've seen a few added cow files and changes made since last release, will a new one be provided anytime soon?

**Comment by apjanke** [comment]
Behold, [cowsay 3.8.0](https://github.com/cowsay-org/cowsay/releases/tag/v3.8.0)!

https://github.com/cowsay-org/cowsay/releases/tag/v3.8.0

Sorry for the slowness here. Been busy at the day job, and I had a hard time figuring out the AsciiDoc vs. Asciidoctor problems in the build process. Think that's sorted now.
