### ISSUE TITLE
The   master  branch of   brew  does not contain the path   CODEOFCONDUCT.md.

### ISSUE THREAD

**Issue by vimnux** [cowsay-org/cowsay#47]
The link "Mac Homebrew's Code of Conduct" on your "Code of conduct" page gives a 404 (Not Found) error.

**Comment by apjanke** [comment]
Fixed in https://github.com/cowsay-org/cowsay/commit/11f2a823241bb19537f8e8df43f46fb1f95d4260.

Thanks!
