### ISSUE TITLE
Unify prefix handling for installed and in-repo behavior

### ISSUE THREAD

**Issue by apjanke** [cowsay-org/cowsay#55]
The thing where cowsay has different behavior and path handling for the running-from-repo (or "source" tree) case and installed case is a bit of a problem. Makes testing harder, e.g. for https://github.com/cowsay-org/cowsay/issues/49. I think it would be better to unify this behavior and have fewer different code ptahs.

## Current situation

Cowsay detects whether it is installed by testing whether the parent directory is named "bin". If it is, it is installed; if not it's running from repo. It sets its prefix and prefix-relative paths differently in this case, and detects its etc dir differently.

* In the installed case, it uses `$prefix/share/cowsay` as its data dir. In the in-repo case, it's just `$prefix/share`, and $prefix is the repo root.
* It special cases $prefix = `/usr`: if it's `/usr`, then $etc is `/etc`; otherwise it's `$prefix/etc`. With a further special case that if running in-repo, then $etc is `/usr/local/etc`.

The file location is detected using Perl's `__FILE__`. I think that doesn't give you the _actual_ path, but what was used on the command line. E.g., if I throw in some diagnostic code:

```
sub pick_cowpath {
    my $parent_dir = dirname(__FILE__);
    my $this_file = __FILE__;
    print "__FILE__ = $this_file\n";
    print "parent_dir = $parent_dir\n";
```

I get:

```
[cowsay] $ ./cowsay hello
__FILE__ = ./cowsay
parent_dir = .
```

When installed with `make install`:

```
[cowsay] $ which cowsay
/usr/local/bin/cowsay
[cowsay] $ cowsay hello
__FILE__ = /usr/local/bin/cowsay
parent_dir = /usr/local/bin
 _______
< hello >
```

But, if I cd over to where the installed cowsay is:

```
[cowsay] $ cd /usr/local/bin
[bin] $ ./cowsay hello
__FILE__ = ./cowsay
parent_dir = .
cowsay: Could not find cowfile for 'default.cow'!
[bin] $
```

## Plans

Let's unify this by making the repo dir layout match the prefix dir layout, to reduce special casing. Move `cowsay` and other commands to a `bin/` inside the repo, and `share/cows` to `share/cowsay/cows`. Remove the "is parent dir named `bin`" is-installed detection logic.

As for how to handle /etc detection, that needs to get more sophisticated - different systems have different handling for whether `/etc` should be used as the config dir for under-prefix programs, or `$prefix/etc`. Probably needs to be a build-time option, with a build step that bakes it in.

For now, I think we can handle it by changing the /etc detection logic: Look in `$prefix/etc` first and then `/etc`, and either merge the configs, or take the first one that exists.

See discussion in https://github.com/cowsay-org/cowsay/pull/26, starting at https://github.com/cowsay-org/cowsay/pull/26#issuecomment-2297422575, about the $etc stuff, install, and build steps.

**Comment by apjanke** [comment]
Did in https://github.com/cowsay-org/cowsay/commit/570be8de68bac34356c1aaecdac38a11b007a375. Should go out in 3.8.3. Will handle the `/etc` vs. `$prefix/etc` stuff separately.

I think that's good enough for now. Closing as Fixed.

**Comment by ndim** [comment]
@ndim Note to self to take a look at this at some time in the future.
