### ISSUE TITLE
Update homebrew installation

### ISSUE THREAD

**Issue by botantony** [cowsay-org/cowsay#70]
This package was included in the official [homebrew repository](https://formulae.brew.sh/formula/cowsay). I think it would be nice to update the respective sections in [README](https://github.com/cowsay-org/cowsay?tab=readme-ov-file#installation-using-homebrew) and on the [webpage](https://github.com/cowsay-org/cowsay-www).

**Comment by apjanke** [comment]
Whaaat? Sweet!

There it is: https://github.com/Homebrew/homebrew-core/commit/4e775971e427fb625a3c06a0f8620a2cccca262e

<img width="1090" alt="image" src="https://github.com/user-attachments/assets/8637eba6-7c0d-4f43-92f3-9085bdcbbffa">

I'll update our doco. Thanks for the heads up!

**Comment by botantony** [comment]
Closed per #71

**Comment by apjanke** [comment]
Updated on the [cowsay.diamonds web site](https://cowsay.diamonds) in https://github.com/cowsay-org/cowsay-www/commit/42040609ffeca5d53f5d9944cbf53ad6f4d508b1.

Now says:

<img width="734" alt="image" src="https://github.com/user-attachments/assets/5d5a927b-d460-40c3-b9cb-eb3c36c648ef">

**Comment by botantony** [comment]
There is a problem with [this link](https://github.com/cowsay-org/cowsay-www/blob/b2a71c2f2152a1972e2c45833c5ae374e32235d9/docs/index.md?plain=1#L36): it leads to `https://github.com/cowsay/homebrew-cowsay-org` instead of `https://github.com/cowsay-org/homebrew-cowsay`

**Comment by apjanke** [comment]
D'oh! Fixed in https://github.com/cowsay-org/cowsay-www/commit/588fda5acb44a70a6f46f235a2bb7ee1bb3ff8aa. Thanks.
